name: image-sync
run-name: syncing docker images
on:
  push:
    branches: [main]

env:
  IMAGE_SYNCER_VERSION: v1.5.2

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run: |
          docker login -u developerxu -p jy@wjgz#0122
      # - name: test docker push
      #   run: |
      #     docker pull registry.k8s.io/metrics-server/metrics-server:v0.6.4
      #     docker tag registry.k8s.io/metrics-server/metrics-server:v0.6.4 developerxu/metrics-server:v0.6.4
      #     docker push developerxu/metrics-server:v0.6.4
      - name: install image-sync tool
        run: |
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
          tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz

      - name: sync images
        run: ./image-syncer --auth=./auth.json --images=./images.json --retries=3
